sudo: required

language: bash

services:
  - docker

env:
  - BRANCH=lts VERSION=6.7.5
  - BRANCH=lts VERSION=6.7.5 VARIANT=alpine
  - BRANCH=latest VERSION=7.3
  - BRANCH=latest VERSION=7.3 VARIANT=alpine

script:
  - tag="${BRANCH}${VARIANT:+-$VARIANT}"
  - cd "$tag"
  - docker build -t "sonarqube-ce:$tag" .
  - docker images

notifications:
  email: false
