sudo: required

language: bash

services:
  - docker

env:
  - VERSION=6.7.5
  - VERSION=6.7.5 VARIANT=alpine
  - VERSION=7.1
  - VERSION=7.1 VARIANT=alpine

script:
  - v="${VERSION}${VARIANT:+-$VARIANT}"
  - cd "$v"
  - docker build -t "sonarqube-$v" .
  - docker images

notifications:
  email: false
